// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSynteticMonitoringProbe(args: GetSynteticMonitoringProbeArgs, opts?: pulumi.InvokeOptions): Promise<GetSynteticMonitoringProbeResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("grafana:/getSynteticMonitoringProbe:getSynteticMonitoringProbe", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getSynteticMonitoringProbe.
 */
export interface GetSynteticMonitoringProbeArgs {
    name: string;
}

/**
 * A collection of values returned by getSynteticMonitoringProbe.
 */
export interface GetSynteticMonitoringProbeResult {
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly latitude: number;
    readonly longitude: number;
    readonly name: string;
    readonly public: boolean;
    readonly region: string;
    readonly tenantId: number;
}

export function getSynteticMonitoringProbeOutput(args: GetSynteticMonitoringProbeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSynteticMonitoringProbeResult> {
    return pulumi.output(args).apply(a => getSynteticMonitoringProbe(a, opts))
}

/**
 * A collection of arguments for invoking getSynteticMonitoringProbe.
 */
export interface GetSynteticMonitoringProbeOutputArgs {
    name: pulumi.Input<string>;
}
